// ========== Configuration ==========
const API_BASE = window.location.origin;
const WS_BASE = API_BASE.replace(/^http/, "ws");

// ========== State ==========
const state = {
  logWs: null,
  _previewPath: null,
  autoScroll: true,
};

// ========== DOM Helpers ==========
const $ = (sel) => document.querySelector(sel);
const $$ = (sel) => document.querySelectorAll(sel);

const els = {};
function cacheDom() {
  els.fileTree = $("#file-tree");
  els.refreshBtn = $("#refresh-btn");
  els.uploadInput = $("#upload-input");
  els.logsContainer = $("#logs-container");
  els.logsTitle = $("#logs-title");
  els.processStatus = $("#process-status");
  els.clearLogsBtn = $("#clear-logs-btn");
  els.scrollBottomBtn = $("#scroll-bottom-btn");
  els.filePanel = $("#file-panel");
  els.resizeHandle = $("#resize-handle");
  // Modal
  els.filePreviewModal = $("#file-preview-modal");
  els.filePreviewTitle = $("#file-preview-title");
  els.filePreviewBody = $("#file-preview-body");
  els.fileDownloadBtn = $("#file-download-btn");
  els.filePreviewClose = $("#file-preview-close");
}

// ========== API Helper ==========
async function api(path, options = {}) {
  const url = `${API_BASE}${path}`;
  const resp = await fetch(url, {
    headers: { "Content-Type": "application/json", ...options.headers },
    ...options,
    cache: "no-store",
  });
  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`API error ${resp.status}: ${text}`);
  }
  if (resp.status === 204) return null;
  return resp.json();
}

// ========== Markdown / Code Rendering ==========
function renderMarkdown(text) {
  if (typeof marked !== "undefined") {
    marked.setOptions({ breaks: true, gfm: true });
    return marked.parse(text);
  }
  return escapeHtml(text).replace(/\n/g, "<br>");
}

function escapeHtml(str) {
  const div = document.createElement("div");
  div.textContent = str;
  return div.innerHTML;
}

function highlightCode(el) {
  if (typeof hljs !== "undefined") {
    el.querySelectorAll("pre code").forEach((block) => {
      hljs.highlightElement(block);
    });
  }
}

// ========== File Explorer ==========
async function loadFileTree() {
  try {
    const tree = await api("/api/files/tree");
    if (!tree || tree.length === 0) {
      els.fileTree.innerHTML =
        '<div class="file-tree-empty">📂 No files yet.<br>Files generated by Copilot will appear here.</div>';
      return;
    }
    renderFileTree(tree, els.fileTree, 0);
  } catch (e) {
    els.fileTree.innerHTML =
      '<div class="file-tree-empty">Could not load files.</div>';
  }
}

function renderFileTree(nodes, container, depth) {
  container.innerHTML = "";
  nodes.forEach((node) => {
    const item = document.createElement("div");
    item.classList.add("tree-item");
    item.style.setProperty("--depth", depth);

    const icon = node.is_folder ? "📁" : getFileIcon(node.name);
    const actionBtns = node.is_folder
      ? '<button class="tree-action-btn" title="Download ZIP">⤓</button>'
      : '<button class="tree-action-btn" title="Download">⤓</button>';

    item.innerHTML = `
            <span class="tree-icon">${node.is_folder ? "▶" : ""} ${icon}</span>
            <span class="tree-name">${escapeHtml(node.name)}</span>
            <span class="tree-actions">
                ${actionBtns}
                <button class="tree-action-btn danger" title="Delete">✕</button>
            </span>
        `;

    // Delete button
    const deleteBtn = item.querySelector(".tree-action-btn.danger");
    deleteBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      deleteFile(node.path, node.name, node.is_folder);
    });

    // Download button
    const dlBtn = item.querySelector(".tree-action-btn:not(.danger)");
    if (dlBtn) {
      dlBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        const dlPath = node.is_folder ? `${node.path}/` : node.path;
        window.open(`${API_BASE}/api/files/download/${dlPath}`, "_blank");
      });
    }

    if (node.is_folder) {
      const children = document.createElement("div");
      children.classList.add("tree-children");
      if (node.children && node.children.length > 0) {
        renderFileTree(node.children, children, depth + 1);
      }

      item.onclick = (e) => {
        e.stopPropagation();
        const isExpanded = children.classList.toggle("expanded");
        const arrow = item.querySelector(".tree-icon");
        arrow.innerHTML = `${isExpanded ? "▼" : "▶"} 📁`;
      };

      container.appendChild(item);
      container.appendChild(children);
    } else {
      item.onclick = () => previewFile(node.path, node.name);
      container.appendChild(item);
    }
  });
}

async function deleteFile(path, name, isFolder) {
  const type = isFolder ? "folder" : "file";
  if (!confirm(`Delete ${type} "${name}"?`)) return;
  try {
    await api(`/api/files/${path}`, { method: "DELETE" });
    loadFileTree();
  } catch (e) {
    alert("Failed to delete: " + e.message);
  }
}

async function uploadFiles(files) {
  for (const file of files) {
    const formData = new FormData();
    formData.append("file", file);
    try {
      await fetch(`${API_BASE}/api/files/upload?path=`, {
        method: "POST",
        body: formData,
      });
    } catch (e) {
      alert("Failed to upload: " + e.message);
    }
  }
  loadFileTree();
}

function getFileIcon(name) {
  const ext = name.split(".").pop().toLowerCase();
  const icons = {
    md: "📝",
    json: "📋",
    py: "🐍",
    js: "📜",
    ts: "📜",
    html: "🌐",
    css: "🎨",
    txt: "📄",
    yaml: "⚙️",
    yml: "⚙️",
    zip: "📦",
    png: "🖼️",
    jpg: "🖼️",
    jpeg: "🖼️",
    svg: "🖼️",
    pdf: "📕",
    sh: "🔧",
    dockerfile: "🐳",
  };
  return icons[ext] || "📄";
}

// ========== File Preview Modal ==========
async function previewFile(path, name) {
  try {
    const resp = await fetch(`${API_BASE}/api/files/content/${path}`);
    const text = await resp.text();
    const ext = name.split(".").pop().toLowerCase();

    els.filePreviewTitle.textContent = name;
    state._previewPath = path;

    if (ext === "md") {
      els.filePreviewBody.innerHTML = `<div class="markdown-content">${renderMarkdown(text)}</div>`;
    } else {
      const pre = document.createElement("pre");
      const code = document.createElement("code");
      code.textContent = text;
      if (
        ["py", "js", "ts", "json", "yaml", "yml", "html", "css", "sh"].includes(
          ext,
        )
      ) {
        code.classList.add(`language-${ext === "yml" ? "yaml" : ext}`);
      }
      pre.appendChild(code);
      els.filePreviewBody.innerHTML = "";
      els.filePreviewBody.appendChild(pre);
      highlightCode(els.filePreviewBody);
    }

    els.filePreviewModal.classList.remove("hidden");
  } catch (e) {
    console.error("Failed to preview file:", e);
  }
}

function downloadFile() {
  if (state._previewPath) {
    window.open(
      `${API_BASE}/api/files/download/${state._previewPath}`,
      "_blank",
    );
  }
}

// ========== Process Logs ==========
function formatTime(ts) {
  const d = new Date(ts * 1000);
  return d.toLocaleTimeString("en-US", {
    hour12: false,
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });
}

function addLogEntry(entry) {
  const container = els.logsContainer;

  // Remove empty state if present
  const empty = container.querySelector(".logs-empty");
  if (empty) empty.remove();

  const div = document.createElement("div");

  switch (entry.type) {
    case "process_start": {
      div.className = "log-entry process-start";
      div.innerHTML = `
                <span class="log-time">${formatTime(entry.ts)}</span>
                <span class="log-content">
                    <span class="log-label">▶ STARTED</span>
                    ${entry.model ? ` <span style="color:var(--text-secondary)">[${escapeHtml(entry.model)}]</span>` : ""}
                    <br>${escapeHtml(entry.prompt || "")}
                </span>
            `;
      setProcessStatus("running");
      break;
    }
    case "process_end": {
      div.className = "log-entry process-end";
      div.innerHTML = `
                <span class="log-time">${formatTime(entry.ts)}</span>
                <span class="log-content"><span class="log-label">✓ COMPLETED</span></span>
            `;
      setProcessStatus("idle");
      // Auto-refresh file tree after a process completes
      setTimeout(() => loadFileTree(), 1000);
      break;
    }
    case "tool_start": {
      div.className = "log-entry tool-start";
      div.innerHTML = `
                <span class="log-time">${formatTime(entry.ts)}</span>
                <span class="log-content">
                    <span class="log-label">⚡ ${escapeHtml(entry.tool || "")}</span>
                    ${entry.description ? ` — ${escapeHtml(entry.description)}` : ""}
                </span>
            `;
      break;
    }
    case "text_delta": {
      // Batch text deltas into the current text block
      const lastEntry = container.querySelector(
        ".log-entry.text-delta:last-of-type",
      );
      if (lastEntry) {
        const content = lastEntry.querySelector(".log-content");
        content.textContent += entry.content;
        scrollLogsIfNeeded();
        return;
      }
      div.className = "log-entry text-delta";
      div.innerHTML = `
                <span class="log-time">${formatTime(entry.ts)}</span>
                <span class="log-content">${escapeHtml(entry.content || "")}</span>
            `;
      break;
    }
    case "ping":
    case "snapshot":
      return; // skip
    default:
      return;
  }

  container.appendChild(div);
  scrollLogsIfNeeded();
}

function renderLogSnapshot(logs) {
  els.logsContainer.innerHTML = "";
  if (!logs || logs.length === 0) {
    showLogsEmpty();
    return;
  }
  logs.forEach((entry) => addLogEntry(entry));
}

function showLogsEmpty() {
  els.logsContainer.innerHTML = `
        <div class="logs-empty">
            <div class="logs-empty-icon">📡</div>
            <div>No process activity yet.</div>
            <div style="font-size: 12px; margin-top: 4px;">Commands running via Telegram or the API will appear here in real time.</div>
        </div>
    `;
}

function setProcessStatus(status) {
  els.processStatus.className = `status-badge ${status}`;
  els.processStatus.textContent = status === "running" ? "Running" : "Idle";
}

function scrollLogsIfNeeded() {
  if (state.autoScroll) {
    els.logsContainer.scrollTop = els.logsContainer.scrollHeight;
  }
}

function clearLogs() {
  showLogsEmpty();
}

// ========== Logs WebSocket ==========
function connectLogsWebSocket() {
  if (state.logWs && state.logWs.readyState === WebSocket.OPEN) return;

  state.logWs = new WebSocket(`${WS_BASE}/api/logs/stream`);

  state.logWs.onmessage = (event) => {
    const data = JSON.parse(event.data);

    if (data.type === "snapshot") {
      // Initial load
      renderLogSnapshot(data.logs);
      if (data.active_process) {
        setProcessStatus("running");
      }
      return;
    }

    addLogEntry(data);
  };

  state.logWs.onclose = () => {
    console.log("Logs WS disconnected, reconnecting...");
    setTimeout(connectLogsWebSocket, 3000);
  };

  state.logWs.onerror = (err) => {
    console.error("Logs WS error:", err);
  };
}

// ========== Resize Handle ==========
function initResize() {
  const handle = els.resizeHandle;
  if (!handle) return;

  let startX, startWidth;

  handle.addEventListener("mousedown", (e) => {
    e.preventDefault();
    startX = e.clientX;
    startWidth = els.filePanel.offsetWidth;
    handle.classList.add("dragging");
    document.body.style.cursor = "col-resize";
    document.body.style.userSelect = "none";

    const onMouseMove = (e) => {
      const delta = e.clientX - startX;
      const newWidth = Math.max(220, Math.min(600, startWidth + delta));
      els.filePanel.style.width = newWidth + "px";
    };

    const onMouseUp = () => {
      handle.classList.remove("dragging");
      document.body.style.cursor = "";
      document.body.style.userSelect = "";
      document.removeEventListener("mousemove", onMouseMove);
      document.removeEventListener("mouseup", onMouseUp);
    };

    document.addEventListener("mousemove", onMouseMove);
    document.addEventListener("mouseup", onMouseUp);
  });
}

// ========== Auto-scroll detection ==========
function initAutoScroll() {
  els.logsContainer.addEventListener("scroll", () => {
    const { scrollTop, scrollHeight, clientHeight } = els.logsContainer;
    state.autoScroll = scrollHeight - scrollTop - clientHeight < 40;
  });
}

// ========== Event Listeners ==========
function initEventListeners() {
  // File explorer
  els.refreshBtn.addEventListener("click", loadFileTree);

  els.uploadInput.addEventListener("change", (e) => {
    if (e.target.files && e.target.files.length > 0) {
      uploadFiles(e.target.files);
      e.target.value = "";
    }
  });

  // Logs
  els.clearLogsBtn.addEventListener("click", clearLogs);
  els.scrollBottomBtn.addEventListener("click", () => {
    state.autoScroll = true;
    els.logsContainer.scrollTop = els.logsContainer.scrollHeight;
  });

  // File preview modal
  els.filePreviewClose.addEventListener("click", () =>
    els.filePreviewModal.classList.add("hidden"),
  );
  els.fileDownloadBtn.addEventListener("click", downloadFile);
  els.filePreviewModal.addEventListener("click", (e) => {
    if (e.target === els.filePreviewModal)
      els.filePreviewModal.classList.add("hidden");
  });
}

// ========== Init ==========
async function init() {
  cacheDom();
  initEventListeners();
  initResize();
  initAutoScroll();

  showLogsEmpty();
  connectLogsWebSocket();

  await loadFileTree();

  // Periodically refresh file tree (every 30s)
  setInterval(loadFileTree, 30000);
}

document.addEventListener("DOMContentLoaded", init);
